package main

import (
	"flag"
	"fmt"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/dave/jennifer/jen"
	"golang.org/x/tools/go/packages"
)

var (
	Type     string
	Pkg      string
	Filename string

	Prefix string
)

type node struct {
	name         string
	typeDef      types.Type
	isCompressed bool
	single       bool
	children     map[string]*node
}

// splitType splits "github.com/some/pkg.TypeName" into ("github.com/some/pkg", "TypeName").
// It also accepts a bare "TypeName" (no dot separator) and loads from the current directory.
func splitType(s string) (pkgPath, typeName string, err error) {
	dot := strings.LastIndex(s, ".")
	if dot < 0 {
		return ".", s, nil
	}
	return s[:dot], s[dot+1:], nil
}

func main() {
	flag.StringVar(&Prefix, "prefix", "", "the global etcd key prefix")
	flag.StringVar(&Type, "type", "", "fully qualified type to analyse, e.g. github.com/some/pkg.Config (required)")
	flag.StringVar(&Pkg, "pkg", "", "output package name (defaults to $GOPACKAGE)")
	flag.StringVar(&Filename, "out", "", "output file (default: <type>_gen.go in current dir)")
	flag.Parse()

	if Type == "" {
		flag.Usage()
		os.Exit(1)
	}

	if Pkg == "" {
		Pkg = os.Getenv("GOPACKAGE")
	}

	if Pkg == "" {
		log.Fatal("output package name required: set -pkg or run via go:generate")
	}

	if Filename == "" {
		Filename = strings.ToLower(Type) + "_gen.go"
	}

	pkgPath, typeName, err := splitType(Type)
	if err != nil {
		log.Fatalf("invalid -type %q: %v", Type, err)
	}

	cfg := &packages.Config{
		Mode: packages.NeedName |
			packages.NeedTypes |
			packages.NeedTypesInfo |
			packages.NeedSyntax |
			packages.NeedImports,
		Dir: ".",
	}

	pkgs, err := packages.Load(cfg, pkgPath)
	if err != nil {
		log.Fatalf("loading package: %v", err)
	}
	if packages.PrintErrors(pkgs) > 0 {
		os.Exit(1)
	}

	pkg := pkgs[0]

	obj := pkg.Types.Scope().Lookup(typeName)
	if obj == nil {
		log.Fatalf("type %q not found in package %s", typeName, pkg.PkgPath)
	}

	named, ok := obj.Type().(*types.Named)
	if !ok {
		log.Fatalf("%q is not a named type", typeName)
	}

	root, err := buildNode(named.Obj().Name(), named.Underlying(), false)
	if err != nil {
		log.Fatalf("analysing type: %v", err)
	}

	f := jen.NewFile(Pkg)
	f.PackageComment("Code generated by https://github.com/NHAS/tetcd, DO NOT EDIT.")

	for _, m := range buildStructs(root, "", "github.com/NHAS/tetcd/paths", "github.com/NHAS/tetcd/codecs") {
		f.Add(m)
		f.Null()
	}

	if err := f.Save(Filename); err != nil {
		log.Fatalf("saving %s: %v", Filename, err)
	}

	fmt.Fprintf(os.Stderr, "tetcd-gen: wrote %s\n", Filename)
}

// ---------------------------------------------------------------------------
// Type walking
// ---------------------------------------------------------------------------

func buildNode(name string, t types.Type, compress bool) (*node, error) {
	if p, ok := t.(*types.Pointer); ok {
		t = p.Elem().Underlying()
	}

	result := &node{
		name:         name,
		typeDef:      t,
		single:       true,
		isCompressed: compress,
		children:     map[string]*node{},
	}

	strct, ok := t.(*types.Struct)
	if !ok {
		return result, nil
	}

	for i := range strct.NumFields() {
		field := strct.Field(i)
		tetcdTag := reflect.StructTag(strct.Tag(i)).Get("tetcd")

		if strings.Contains(tetcdTag, "-") {
			continue
		}

		if !field.Exported() {
			continue
		}

		isCompress := strings.Contains(tetcdTag, "compress")
		ft := field.Type()
		ut := ft.Underlying()

		switch concrete := ut.(type) {
		case *types.Interface:
			return nil, fmt.Errorf("use of abstract types for concrete storage: %s", field.Name())

		case *types.Struct:
			child, err := buildNode(field.Name(), ut, false)
			if err != nil {
				return nil, err
			}

			if field.Anonymous() {
				for k, v := range child.children {
					result.children[k] = v
				}
				continue
			}

			result.children[field.Name()] = child

		case *types.Map:
			if !isKind(concrete.Key(), types.String) {
				return nil, fmt.Errorf("unsupported map key type for field %s: must be string", field.Name())
			}

			result.children[field.Name()] = &node{
				name:         field.Name(),
				typeDef:      ft,
				isCompressed: isCompress,
				children:     map[string]*node{},
			}

		case *types.Slice:
			elem := concrete.Elem().Underlying()
			if !isKind(elem, types.String) && !isKind(elem, types.Byte) {
				return nil, fmt.Errorf("unsupported slice element type for field %s: must be string or []byte", field.Name())
			}

			result.children[field.Name()] = &node{
				name:         field.Name(),
				typeDef:      ft,
				isCompressed: isCompress,
				children:     map[string]*node{},
			}

		default:
			result.children[field.Name()] = &node{
				name:     field.Name(),
				typeDef:  ft,
				single:   true,
				children: map[string]*node{},
			}
		}
	}

	return result, nil
}

func isKind(t types.Type, kind types.BasicKind) bool {
	b, ok := t.Underlying().(*types.Basic)
	return ok && b.Kind() == kind
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

func sortedKeys(m map[string]*node) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func buildStructs(root *node, path, pathsPkg, codecsPkg string) []jen.Code {
	var (
		result       []jen.Code
		structFields []jen.Code
	)
	for _, name := range sortedKeys(root.children) {
		child := root.children[name]
		if len(child.children) == 0 {
			continue
		}

		result = append(result, buildStructs(child, filepath.Join(path, root.name), pathsPkg, codecsPkg)...)

		childTypeName := structTypeName(child.name, filepath.Join(path, root.name))
		structFields = append(structFields, jen.Id(child.name).Id(childTypeName))
	}

	typeName := structTypeName(root.name, path)

	result = append(result, jen.Type().Id(typeName).Struct(structFields...))
	result = append(result, generateFunctions(root, path, pathsPkg, codecsPkg)...)

	if path == "" {
		result = append(result,
			jen.Var().Id(root.name).Op("=").Id(typeName).Values(),
		)
	}

	return result
}

func structTypeName(name, path string) string {
	prefix := ""
	if path != "" {
		prefix = filepath.Base(path)
	}
	return "autoType" + prefix + name
}

func getLeafNodes(n *node) []*node {
	var out []*node
	for _, name := range sortedKeys(n.children) {
		child := n.children[name]
		if len(child.children) == 0 {
			out = append(out, child)
		}
	}
	return out
}

func generateFunctions(n *node, path, pathsPkg, codecsPkg string) (result []jen.Code) {
	for _, f := range getLeafNodes(n) {
		result = append(result, generateFunction(f, n, path, pathsPkg, codecsPkg)...)
	}
	return
}

func generateFunction(f *node, parent *node, path, pathsPkg, codecsPkg string) []jen.Code {
	etcdPath := filepath.Join(path, parent.name, f.name)
	if Prefix != "" {
		etcdPath = filepath.Join(Prefix, etcdPath)
	}
	typeName := structTypeName(parent.name, path)
	receiver := jen.Id(typeName)

	switch ut := f.typeDef.Underlying().(type) {
	case *types.Map:
		if f.isCompressed {
			return generatePathFunction(receiver, f, etcdPath, pathsPkg, codecsPkg)
		}
		switch ut.Elem().Underlying().(type) {
		case *types.Slice, *types.Array, *types.Map:
			return generateSliceMapFunction(receiver, f, etcdPath, ut.Elem(), pathsPkg, codecsPkg)
		default:
			return generateMapFunction(receiver, f, etcdPath, ut.Elem(), pathsPkg, codecsPkg)
		}

	case *types.Slice:
		if f.isCompressed {
			return generatePathFunction(receiver, f, etcdPath, pathsPkg, codecsPkg)
		}
		return generateMapFunction(receiver, f, etcdPath, ut.Elem(), pathsPkg, codecsPkg)

	case *types.Array:
		if f.isCompressed {
			return generatePathFunction(receiver, f, etcdPath, pathsPkg, codecsPkg)
		}
		return generateMapFunction(receiver, f, etcdPath, ut.Elem(), pathsPkg, codecsPkg)

	default:
		return generatePathFunction(receiver, f, etcdPath, pathsPkg, codecsPkg)
	}
}

func generatePathFunction(receiver *jen.Statement, f *node, etcdPath, pathsPkg, codecsPkg string) []jen.Code {
	return []jen.Code{
		jen.Commentf("%s() KV should contain type %s", f.name, f.typeDef.String()),
		jen.Func().Params(receiver).Id(f.name).Params().
			Qual(pathsPkg, "Path").Types(typeExpr(f.typeDef)).
			Block(jen.Return(
				jen.Qual(pathsPkg, "NewPath").Call(
					jen.Lit(etcdPath),
					jen.Qual(codecsPkg, "NewJsonCodec").Types(typeExpr(f.typeDef)).Call(),
				),
			)),
	}
}

func generateMapFunction(receiver *jen.Statement, f *node, etcdPath string, valueType types.Type, pathsPkg, codecsPkg string) []jen.Code {
	return []jen.Code{
		jen.Commentf("%s() is a map path with prefix %s, value type %s", f.name, etcdPath, valueType.String()),
		jen.Func().Params(receiver).Id(f.name).Params().
			Qual(pathsPkg, "MapPath").Types(typeExpr(valueType)).
			Block(jen.Return(
				jen.Qual(pathsPkg, "NewMapPath").Call(
					jen.Lit(etcdPath),
					jen.Qual(codecsPkg, "NewJsonCodec").Types(typeExpr(valueType)).Call(),
				),
			)),
	}
}

func generateSliceMapFunction(receiver *jen.Statement, f *node, etcdPath string, valueType types.Type, pathsPkg, codecsPkg string) []jen.Code {
	var elemType types.Type

	switch ut := valueType.Underlying().(type) {
	case *types.Slice:
		elem := ut.Elem().Underlying()
		if !isKind(elem, types.String) && !isKind(elem, types.Byte) {
			log.Fatalf("field %s: map[string][]T only supports []string or []byte", f.name)
		}
		elemType = ut.Elem()

	case *types.Map:
		if !isKind(ut.Key(), types.String) {
			log.Fatalf("field %s: map[string]map[K]V requires string inner key", f.name)
		}
		elemType = ut.Elem()

	default:
		log.Fatalf("field %s: generateSliceMapFunction called with unsupported value type %s", f.name, valueType)
	}

	return []jen.Code{
		jen.Commentf("%s() is a slice map path with prefix %s, value type %s", f.name, etcdPath, elemType.String()),
		jen.Func().Params(receiver).Id(f.name).Params().
			Qual(pathsPkg, "MapSlicePath").Types(typeExpr(elemType)).
			Block(jen.Return(
				jen.Qual(pathsPkg, "NewMapSlicePath").Call(
					jen.Lit(etcdPath),
					jen.Qual(codecsPkg, "NewJsonCodec").Types(typeExpr(elemType)).Call(),
				),
			)),
	}
}

// ---------------------------------------------------------------------------
// types.Type -> jen.Code
// ---------------------------------------------------------------------------

func typeExpr(t types.Type) jen.Code {
	switch ut := t.(type) {
	case *types.Pointer:
		return jen.Op("*").Add(typeExpr(ut.Elem()))

	case *types.Slice:
		return jen.Index().Add(typeExpr(ut.Elem()))

	case *types.Array:
		return jen.Index(jen.Lit(int(ut.Len()))).Add(typeExpr(ut.Elem()))

	case *types.Map:
		return jen.Map(typeExpr(ut.Key())).Add(typeExpr(ut.Elem()))

	case *types.Named:
		pkg := ut.Obj().Pkg()
		if pkg != nil {
			return jen.Qual(pkg.Path(), ut.Obj().Name())
		}
		return jen.Id(ut.Obj().Name())

	case *types.Basic:
		return jen.Id(ut.Name())

	default:
		return jen.Id(t.String())
	}
}
