package main

import (
	"flag"
	"fmt"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/dave/jennifer/jen"
	"golang.org/x/tools/go/packages"
)

var (
	FullyQualifiedType string
	PkgPath            string
	TypeName           string

	Pkg      string
	Filename string

	Prefix string
)

type node struct {
	name      string
	typeDef   types.Type
	namedType *types.Named // the declared named type, nil for anonymous structs

	isCompressed bool
	single       bool
	children     map[string]*node
}

// splitType splits "github.com/some/pkg.TypeName" into ("github.com/some/pkg", "TypeName").
// It also accepts a bare "TypeName" (no dot separator) and loads from the current directory.
func splitType(s string) (pkgPath, typeName string, err error) {
	dot := strings.LastIndex(s, ".")
	if dot < 0 {
		return ".", s, nil
	}
	return s[:dot], s[dot+1:], nil
}

func main() {
	flag.StringVar(&Prefix, "prefix", "", "the global etcd key prefix")
	flag.StringVar(&FullyQualifiedType, "type", "", "fully qualified type to analyse, e.g. github.com/some/pkg.Config (required)")
	flag.StringVar(&Pkg, "pkg", "", "output package name (defaults to $GOPACKAGE)")
	flag.StringVar(&Filename, "out", "", "output file (default: <type>_gen.go in current dir)")
	flag.Parse()

	if FullyQualifiedType == "" {
		flag.Usage()
		os.Exit(1)
	}

	if Pkg == "" {
		Pkg = os.Getenv("GOPACKAGE")
	}

	if Pkg == "" {
		log.Fatal("output package name required: set -pkg or run via go:generate")
	}

	if Filename == "" {
		Filename = strings.ToLower(FullyQualifiedType) + "_gen.go"
	}

	var err error
	PkgPath, TypeName, err = splitType(FullyQualifiedType)
	if err != nil {
		log.Fatalf("invalid -type %q: %v", FullyQualifiedType, err)
	}

	cfg := &packages.Config{
		Mode: packages.NeedName |
			packages.NeedTypes |
			packages.NeedTypesInfo |
			packages.NeedSyntax |
			packages.NeedImports,
		Dir: ".",
	}

	pkgs, err := packages.Load(cfg, PkgPath)
	if err != nil {
		log.Fatalf("loading package: %v", err)
	}
	if packages.PrintErrors(pkgs) > 0 {
		os.Exit(1)
	}

	pkg := pkgs[0]

	obj := pkg.Types.Scope().Lookup(TypeName)
	if obj == nil {
		log.Fatalf("type %q not found in package %s", TypeName, pkg.PkgPath)
	}

	named, ok := obj.Type().(*types.Named)
	if !ok {
		log.Fatalf("%q is not a named type", TypeName)
	}

	root, err := buildNode(named.Obj().Name(), named.Underlying(), false)
	if err != nil {
		log.Fatalf("analysing type: %v", err)
	}

	f := jen.NewFile(Pkg)
	f.PackageComment("Code generated by https://github.com/NHAS/tetcd, DO NOT EDIT.")

	for _, m := range buildStructs(root, "", "github.com/NHAS/tetcd/paths", "github.com/NHAS/tetcd/codecs") {
		f.Add(m)
		f.Null()
	}

	if err := f.Save(Filename); err != nil {
		log.Fatalf("saving %s: %v", Filename, err)
	}

	fmt.Fprintf(os.Stderr, "tetcd-gen: wrote %s\n", Filename)
}

// ---------------------------------------------------------------------------
// Type walking
// ---------------------------------------------------------------------------

func buildNode(name string, t types.Type, compress bool) (*node, error) {
	if p, ok := t.(*types.Pointer); ok {
		t = p.Elem()
	}

	var named *types.Named
	if n, ok := t.(*types.Named); ok {
		named = n
		t = n.Underlying()
	}

	result := &node{
		name:         name,
		typeDef:      t,
		namedType:    named,
		single:       true,
		isCompressed: compress,
		children:     map[string]*node{},
	}

	strct, ok := t.(*types.Struct)
	if !ok {
		return result, nil
	}

	for i := range strct.NumFields() {
		field := strct.Field(i)
		tetcdTag := reflect.StructTag(strct.Tag(i)).Get("tetcd")

		if strings.Contains(tetcdTag, "-") {
			continue
		}

		if !field.Exported() && !field.Anonymous() {
			continue
		}

		isCompress := strings.Contains(tetcdTag, "compress")
		ft := field.Type()

		switch concrete := ft.Underlying().(type) {
		case *types.Interface:
			return nil, fmt.Errorf("use of abstract types for concrete storage: %s", field.Name())

		case *types.Struct:
			child, err := buildNode(field.Name(), ft, false)
			if err != nil {
				return nil, err
			}

			if field.Anonymous() {
				for k, v := range child.children {
					result.children[k] = v
				}
				continue
			}

			result.children[field.Name()] = child

		case *types.Map:
			if !isKind(concrete.Key(), types.String) {
				return nil, fmt.Errorf("unsupported map key type for field %s: must be string", field.Name())
			}

			result.children[field.Name()] = &node{
				name:         field.Name(),
				typeDef:      ft,
				isCompressed: isCompress,
				children:     map[string]*node{},
			}

		case *types.Slice:
			elem := concrete.Elem().Underlying()
			if !isKind(elem, types.String) && !isKind(elem, types.Byte) {
				return nil, fmt.Errorf("unsupported slice element type for field %s: must be string or []byte", field.Name())
			}

			result.children[field.Name()] = &node{
				name:         field.Name(),
				typeDef:      ft,
				isCompressed: isCompress,
				children:     map[string]*node{},
			}

		default:
			result.children[field.Name()] = &node{
				name:     field.Name(),
				typeDef:  ft,
				single:   true,
				children: map[string]*node{},
			}
		}
	}

	return result, nil
}

func isKind(t types.Type, kind types.BasicKind) bool {
	b, ok := t.Underlying().(*types.Basic)
	return ok && b.Kind() == kind
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

func sortedKeys(m map[string]*node) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func buildStructs(root *node, path, pathsPkg, codecsPkg string) []jen.Code {
	var (
		result       []jen.Code
		structFields []jen.Code
	)
	// generates the auto type fields
	for _, name := range sortedKeys(root.children) {
		child := root.children[name]
		if len(child.children) == 0 {
			continue
		}

		result = append(result, buildStructs(child, filepath.Join(path, root.name), pathsPkg, codecsPkg)...)

		childTypeName := structTypeName(child.name, filepath.Join(path, root.name))
		structFields = append(structFields, jen.Id(child.name).Id(childTypeName))
	}

	typeName := structTypeName(root.name, path)

	result = append(result, jen.Type().Id(typeName).Struct(structFields...))
	result = append(result, generateFunctions(root, path, pathsPkg, codecsPkg)...)

	if path == "" {
		// Root node: emit the var but NOT a Get method
		result = append(result,
			jen.Var().Id(root.name).Op("=").Id(typeName).Values(),
		)
	} else {
		// Non-root nodes with children get a Get method.
		// If this node is an anonymous struct, emit a concrete type alias first.
		if len(root.children) > 0 {
			if root.namedType == nil {
				if _, ok := root.typeDef.(*types.Struct); ok {
					typeName, _ := deriveConcreteTypeName(root, path)
					result = append(result,
						jen.Type().Add(typeName).Add(typeExpr(root.typeDef)),
					)
				}
			}
			result = append(result, generateGetAll(root, path)...)
		}
	}
	return result
}

func deriveConcreteTypeName(n *node, path string) (jen.Code, string) {
	if n.namedType != nil {
		typeName := n.namedType.Obj().Name()

		return jen.Qual(n.namedType.Obj().Pkg().Path(), typeName), typeName
	}
	// Anonymous struct: refers to the generated autoConcrete* type
	prefix := ""
	if path != "" {
		prefix = filepath.Base(path)
	}

	constructedTypeName := "result" + prefix + n.name
	return jen.Id(constructedTypeName), constructedTypeName
}

func generateGetAll(n *node, path string) []jen.Code {
	leaves := collectAllLeaves(n, path)
	if len(leaves) == 0 {
		return nil
	}

	autoTypeName := structTypeName(n.name, path)

	returnType, returnTypeStr := deriveConcreteTypeName(n, path)

	var batches [][]leafWithPath
	for i := 0; i < len(leaves); i += maxOpsPerTxn {
		end := min(i+maxOpsPerTxn, len(leaves))
		batches = append(batches, leaves[i:end])
	}

	var body []jen.Code

	if len(batches) > 1 {
		body = append(body, jen.Var().Id("rev").Int64())
	}

	for batchIdx, batch := range batches {
		batchStmts, handleNames := buildBatchStatementsFromMethods(batchIdx, batch, path, len(batches), n)
		body = append(body, batchStmts...)

		for i, lp := range batch {
			handleName := handleNames[i]
			fieldAccess := buildFieldAccess(jen.Empty(), lp, path, n, false)

			valueMethod := "Value"
			if !lp.leaf.single && !lp.leaf.isCompressed {
				valueMethod = "Entries"
				if ut, ok := lp.leaf.typeDef.Underlying().(*types.Map); ok {
					if sl, ok := ut.Elem().Underlying().(*types.Slice); ok {
						if isKind(sl.Elem().Underlying(), types.String) {
							valueMethod = "Keys"
						}
					}
				}
			}

			body = append(body,
				jen.List(jen.Id("result").Add(fieldAccess), jen.Err()).
					Op("=").Id(handleName).Dot(valueMethod).Call(),
				jen.If(jen.Err().Op("!=").Nil()).Block(
					jen.Return(jen.Id("result"), jen.Err()),
				),
			)
		}
	}

	body = append(body, jen.Return(jen.Id("result"), jen.Nil()))

	fn := jen.Commentf("Get fetches all fields of %s in one or more transactions pinned to the same etcd revision.", returnTypeStr)
	fn2 := jen.Func().
		Params(jen.Id("a").Id(autoTypeName)).
		Id("Get").
		Params(
			jen.Id("ctx").Qual("context", "Context"),
			jen.Id("cli").Op("*").Qual("go.etcd.io/etcd/client/v3", "Client"),
		).
		Params(jen.Id("result").Add(returnType), jen.Id("err").Error()).
		Block(body...)

	return []jen.Code{fn, fn2}
}

// buildBatchStatementsFromMethods emits the txn setup, GetTx calls using the
// generated accessor methods on the autoType receiver, and Commit for one batch.
func buildBatchStatementsFromMethods(batchIdx int, batch []leafWithPath, path string, totalBatches int, root *node) ([]jen.Code, []string) {
	var stmts []jen.Code
	var handleNames []string

	txnVar := fmt.Sprintf("txn%d", batchIdx)
	tetcdPkg := "github.com/NHAS/tetcd"

	stmts = append(stmts,
		jen.Id(txnVar).Op(":=").Qual(tetcdPkg, "NewTxn").Call(jen.Id("ctx"), jen.Id("cli")),
	)

	for i, lp := range batch {
		handleVar := fmt.Sprintf("h%d_%d", batchIdx, i)
		handleNames = append(handleNames, handleVar)

		// Build the method call chain: a.Sub().Leaf()
		// Start from "a" (the receiver), then call each intermediate node's accessor,
		// then the leaf accessor.
		accessorChain := buildFieldAccess(jen.Id("a"), lp, path, root, true)

		txFunc := "GetTx"
		if !lp.leaf.single && !lp.leaf.isCompressed {
			txFunc = "ListTx"
			switch ut := lp.leaf.typeDef.Underlying().(type) {
			case *types.Map:
				switch ut.Elem().Underlying().(type) {

				case *types.Slice, *types.Array, *types.Map:
					txFunc = "DynamicCollectionTx"
				default:
				}
			default:

			}

		}

		var getTxCall *jen.Statement
		if batchIdx > 0 {
			extraOpts := jen.Qual("go.etcd.io/etcd/client/v3", "WithRev").Call(jen.Id("rev"))
			getTxCall = jen.Id(handleVar).Op(":=").Qual(tetcdPkg, txFunc).Call(
				jen.Id(txnVar).Dot("Then").Call(),
				accessorChain,
				extraOpts,
			)
		} else {
			getTxCall = jen.Id(handleVar).Op(":=").Qual(tetcdPkg, txFunc).Call(
				jen.Id(txnVar).Dot("Then").Call(),
				accessorChain,
			)
		}
		stmts = append(stmts, getTxCall)
	}

	stmts = append(stmts,
		jen.If(
			jen.Err().Op(":=").Id(txnVar).Dot("Commit").Call(),
			jen.Err().Op("!=").Nil(),
		).Block(jen.Return(jen.Id("result"), jen.Err())),
	)

	if batchIdx == 0 && totalBatches > 1 {
		stmts = append(stmts,
			jen.Id("rev").Op("=").Id(txnVar).Dot("Rev").Call(),
		)
	}

	return stmts, handleNames
}

// buildFieldAccess returns the jen field selector chain to reach a leaf
// on the concrete result struct (e.g. .Server.Host for result.Server.Host).
// lp.path is the path *above* lp.parentNode (e.g. "Config" for Config.Server.Host).
func buildFieldAccess(codeRoot *jen.Statement, lp leafWithPath, path string, root *node, isFunc bool) jen.Code {
	// lp.path is the full path including parentNode, e.g. "Config/TLS/NestedInTls"
	// Strip the root name prefix to get relative segments.
	rel := strings.TrimPrefix(lp.path, path)
	rel = strings.TrimPrefix(rel, string(filepath.Separator))
	rel = strings.TrimPrefix(rel, root.name)
	rel = strings.TrimPrefix(rel, string(filepath.Separator))

	if rel != "" {
		for p := range strings.SplitSeq(rel, string(filepath.Separator)) {
			codeRoot = codeRoot.Dot(p)
		}
	}

	codeRoot = codeRoot.Dot(lp.leaf.name)
	if isFunc {
		codeRoot = codeRoot.Call()
	}
	return codeRoot
}

// getAllLeafNodes recursively collects all leaf nodes from n, returning them
// together with the path segment needed to build their etcd key.
type leafWithPath struct {
	leaf       *node
	parentNode *node
	path       string // full path from root down to and including parentNode
}

func collectAllLeaves(n *node, path string) []leafWithPath {
	var out []leafWithPath
	currentPath := filepath.Join(path, n.name)
	for _, name := range sortedKeys(n.children) {
		child := n.children[name]
		if len(child.children) == 0 {
			out = append(out, leafWithPath{leaf: child, parentNode: n, path: currentPath})
		} else {
			out = append(out, collectAllLeaves(child, currentPath)...)
		}
	}
	return out
}

const maxOpsPerTxn = 50

func structTypeName(name, path string) string {
	prefix := ""
	if path != "" {
		prefix = filepath.Base(path)
	}
	return "autoType" + prefix + name
}

func getLeafNodes(n *node) []*node {
	var out []*node
	for _, name := range sortedKeys(n.children) {
		child := n.children[name]
		if len(child.children) == 0 {
			out = append(out, child)
		}
	}
	return out
}

func generateFunctions(n *node, path, pathsPkg, codecsPkg string) (result []jen.Code) {
	for _, f := range getLeafNodes(n) {
		result = append(result, generateFunction(f, n, path, pathsPkg, codecsPkg)...)
	}
	return
}

func generateFunction(f *node, parent *node, path, pathsPkg, codecsPkg string) []jen.Code {
	etcdPath := filepath.Join(path, parent.name, f.name)
	if Prefix != "" {
		etcdPath = filepath.Join(Prefix, etcdPath)
	}
	typeName := structTypeName(parent.name, path)
	receiver := jen.Id(typeName)

	switch ut := f.typeDef.Underlying().(type) {
	case *types.Map:
		if f.isCompressed {
			return generatePathFunction(receiver, f, etcdPath, pathsPkg, codecsPkg)
		}
		switch ut.Elem().Underlying().(type) {
		case *types.Slice, *types.Array, *types.Map:
			return generateSliceMapFunction(receiver, f, etcdPath, ut.Elem(), pathsPkg, codecsPkg)
		default:
			return generateMapFunction(receiver, f, etcdPath, ut.Elem(), pathsPkg, codecsPkg)
		}

	case *types.Slice:
		if f.isCompressed {
			return generatePathFunction(receiver, f, etcdPath, pathsPkg, codecsPkg)
		}
		return generateMapFunction(receiver, f, etcdPath, ut.Elem(), pathsPkg, codecsPkg)

	case *types.Array:
		if f.isCompressed {
			return generatePathFunction(receiver, f, etcdPath, pathsPkg, codecsPkg)
		}
		return generateMapFunction(receiver, f, etcdPath, ut.Elem(), pathsPkg, codecsPkg)

	default:
		return generatePathFunction(receiver, f, etcdPath, pathsPkg, codecsPkg)
	}
}

func generatePathFunction(receiver *jen.Statement, f *node, etcdPath, pathsPkg, codecsPkg string) []jen.Code {
	return []jen.Code{
		jen.Commentf("%s() KV should contain type %s", f.name, f.typeDef.String()),
		jen.Func().Params(receiver).Id(f.name).Params().
			Qual(pathsPkg, "Path").Types(typeExpr(f.typeDef)).
			Block(jen.Return(
				jen.Qual(pathsPkg, "NewPath").Call(
					jen.Lit(etcdPath),
					jen.Qual(codecsPkg, "NewJsonCodec").Types(typeExpr(f.typeDef)).Call(),
				),
			)),
	}
}

func generateMapFunction(receiver *jen.Statement, f *node, etcdPath string, valueType types.Type, pathsPkg, codecsPkg string) []jen.Code {
	return []jen.Code{
		jen.Commentf("%s() is a map path with prefix %s, value type %s", f.name, etcdPath, valueType.String()),
		jen.Func().Params(receiver).Id(f.name).Params().
			Qual(pathsPkg, "MapPath").Types(typeExpr(valueType)).
			Block(jen.Return(
				jen.Qual(pathsPkg, "NewMapPath").Call(
					jen.Lit(etcdPath),
					jen.Qual(codecsPkg, "NewJsonCodec").Types(typeExpr(valueType)).Call(),
				),
			)),
	}
}

func generateSliceMapFunction(receiver *jen.Statement, f *node, etcdPath string, valueType types.Type, pathsPkg, codecsPkg string) []jen.Code {
	var elemType types.Type

	presenceOnly := false
	switch ut := valueType.Underlying().(type) {
	case *types.Slice:
		elem := ut.Elem().Underlying()
		if !isKind(elem, types.String) && !isKind(elem, types.Byte) {
			log.Fatalf("field %s: map[string][]T only supports []string or []byte", f.name)
		}
		elemType = ut.Elem()
		presenceOnly = true
	case *types.Map:
		if !isKind(ut.Key(), types.String) {
			log.Fatalf("field %s: map[string]map[K]V requires K to be string", f.name)
		}
		elemType = ut.Elem()

	default:
		log.Fatalf("field %s: generateSliceMapFunction called with unsupported value type %s", f.name, valueType)
	}

	return []jen.Code{
		jen.Commentf("%s() is a slice map path with prefix %s, value type %s", f.name, etcdPath, elemType.String()),
		jen.Func().Params(receiver).Id(f.name).Params().
			Qual(pathsPkg, "MapSlicePath").Types(typeExpr(elemType)).
			Block(jen.Return(
				jen.Qual(pathsPkg, "NewMapSlicePath").Call(
					jen.Lit(etcdPath),
					jen.Qual(codecsPkg, "NewJsonCodec").Types(typeExpr(elemType)).Call(),
					jen.Lit(presenceOnly),
				),
			)),
	}
}

// ---------------------------------------------------------------------------
// types.Type -> jen.Code
// ---------------------------------------------------------------------------

func typeExpr(t types.Type) jen.Code {
	switch ut := t.(type) {
	case *types.Pointer:
		return jen.Op("*").Add(typeExpr(ut.Elem()))

	case *types.Slice:
		return jen.Index().Add(typeExpr(ut.Elem()))

	case *types.Array:
		return jen.Index(jen.Lit(int(ut.Len()))).Add(typeExpr(ut.Elem()))

	case *types.Map:
		return jen.Map(typeExpr(ut.Key())).Add(typeExpr(ut.Elem()))

	case *types.Named:
		pkg := ut.Obj().Pkg()
		if pkg != nil {
			return jen.Qual(pkg.Path(), ut.Obj().Name())
		}
		return jen.Id(ut.Obj().Name())

	case *types.Basic:
		return jen.Id(ut.Name())

	case *types.Struct:
		return structTypeExpr(ut)

	default:
		return jen.Id(t.String())
	}
}

func structTypeExpr(s *types.Struct) jen.Code {
	var fields []jen.Code
	for field := range s.Fields() {
		f := jen.Id(field.Name()).Add(typeExpr(field.Type()))

		if field.Anonymous() {
			f = jen.Add(typeExpr(field.Type()))
		}

		fields = append(fields, f)
	}
	return jen.Struct(fields...)
}
