// Code generated by https://github.com/NHAS/tetcd, DO NOT EDIT.
package main

import (
	"context"

	tetcd "github.com/NHAS/tetcd"
	config "github.com/NHAS/tetcd/cmd/test/config"
	codecs "github.com/NHAS/tetcd/codecs"
	paths "github.com/NHAS/tetcd/paths"
	v3 "go.etcd.io/etcd/client/v3"
)

type autoTypeConfigServer struct{}

// Host() KV should contain type string
func (autoTypeConfigServer) Host() paths.Path[string] {
	return paths.NewPath("wagtest/Config/Server/Host", codecs.NewJsonCodec[string]())
}

// Port() KV should contain type int
func (autoTypeConfigServer) Port() paths.Path[int] {
	return paths.NewPath("wagtest/Config/Server/Port", codecs.NewJsonCodec[int]())
}

// Test() KV should contain type string
func (autoTypeConfigServer) Test() paths.Path[string] {
	return paths.NewPath("wagtest/Config/Server/Test", codecs.NewJsonCodec[string]())
}

// Toaster() KV should contain type string
func (autoTypeConfigServer) Toaster() paths.Path[string] {
	return paths.NewPath("wagtest/Config/Server/Toaster", codecs.NewJsonCodec[string]())
}

// Get fetches all fields of ServerConfig in one or more transactions pinned to the same etcd revision.
func (a autoTypeConfigServer) Get(ctx context.Context, cli *v3.Client) (result config.ServerConfig, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.GetTx(txn0.Then(), a.Host())
	h0_1 := tetcd.GetTx(txn0.Then(), a.Port())
	h0_2 := tetcd.GetTx(txn0.Then(), a.Test())
	h0_3 := tetcd.GetTx(txn0.Then(), a.Toaster())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Host, err = h0_0.Value()
	if err != nil {
		return result, err
	}
	result.Port, err = h0_1.Value()
	if err != nil {
		return result, err
	}
	result.Test, err = h0_2.Value()
	if err != nil {
		return result, err
	}
	result.Toaster, err = h0_3.Value()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypeConfigTLS struct{}

// CertFile() KV should contain type string
func (autoTypeConfigTLS) CertFile() paths.Path[string] {
	return paths.NewPath("wagtest/Config/TLS/CertFile", codecs.NewJsonCodec[string]())
}

// Groups() is a slice map path with prefix wagtest/Config/TLS/Groups, value type string
func (autoTypeConfigTLS) Groups() paths.MapSlicePath[string] {
	return paths.NewMapSlicePath("wagtest/Config/TLS/Groups", codecs.NewJsonCodec[string](), true)
}

// KeyFile() KV should contain type string
func (autoTypeConfigTLS) KeyFile() paths.Path[string] {
	return paths.NewPath("wagtest/Config/TLS/KeyFile", codecs.NewJsonCodec[string]())
}

// Get fetches all fields of TLSConfig in one or more transactions pinned to the same etcd revision.
func (a autoTypeConfigTLS) Get(ctx context.Context, cli *v3.Client) (result config.TLSConfig, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.GetTx(txn0.Then(), a.CertFile())
	h0_1 := tetcd.ListNestedTx(txn0.Then(), a.Groups())
	h0_2 := tetcd.GetTx(txn0.Then(), a.KeyFile())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.CertFile, err = h0_0.Value()
	if err != nil {
		return result, err
	}
	result.Groups, err = h0_1.Entries()
	if err != nil {
		return result, err
	}
	result.KeyFile, err = h0_2.Value()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypeConfig struct {
	Server autoTypeConfigServer
	TLS    autoTypeConfigTLS
}

// Labels() is a map path with prefix wagtest/Config/Labels, value type string
func (autoTypeConfig) Labels() paths.MapPath[string] {
	return paths.NewMapPath("wagtest/Config/Labels", codecs.NewJsonCodec[string]())
}

// Name() KV should contain type string
func (autoTypeConfig) Name() paths.Path[string] {
	return paths.NewPath("wagtest/Config/Name", codecs.NewJsonCodec[string]())
}

// Tags() KV should contain type []string
func (autoTypeConfig) Tags() paths.Path[[]string] {
	return paths.NewPath("wagtest/Config/Tags", codecs.NewJsonCodec[[]string]())
}

var Config = autoTypeConfig{}
