// Code generated by https://github.com/NHAS/tetcd, DO NOT EDIT.
package main

import (
	"context"
	tetcd "github.com/NHAS/tetcd"
	another "github.com/NHAS/tetcd/cmd/test/another"
	config "github.com/NHAS/tetcd/cmd/test/config"
	codecs "github.com/NHAS/tetcd/codecs"
	paths "github.com/NHAS/tetcd/paths"
	tree "github.com/NHAS/tetcd/tree"
	watch "github.com/NHAS/tetcd/watch"
	specialist "github.com/NHAS/tetcd/watch/specialist"
	v3 "go.etcd.io/etcd/client/v3"
)

type autoTypeConfigDummy struct{}

// Something5() KV should contain type string
func (autoTypeConfigDummy) Something5() paths.Path[string] {
	return paths.NewPath("wagtest/Config/Dummy/Something5", codecs.NewJsonCodec[string]())
}

type resultConfigDummy struct {
	Something5 string
}

// Get fetches all fields of resultConfigDummy in one or more transactions pinned to the same etcd revision.
func (a autoTypeConfigDummy) GetWithFail(ctx context.Context, cli *v3.Client, failEarly bool, opts ...tetcd.TxnOp) (result resultConfigDummy, err error) {
	txn0 := tetcd.NewTxn(ctx, cli, opts...)
	h0_0 := tetcd.GetTx(txn0.Then(), a.Something5())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Something5, err = h0_0.Value()
	if err != nil && failEarly {
		return result, err
	}
	return result, nil
}
func (a autoTypeConfigDummy) Get(ctx context.Context, cli *v3.Client, opts ...tetcd.TxnOp) (result resultConfigDummy, err error) {
	return a.GetWithFail(ctx, cli, false, opts...)
}

// Watch returns a Watcher that emits the full resultConfigDummy struct whenever any sub-key changes.
func (a autoTypeConfigDummy) Watch(ctx context.Context, cli *v3.Client) *watch.Watcher[resultConfigDummy] {
	return specialist.NewAllWatcher(ctx, cli, "wagtest/Config/Dummy/", a.GetWithFail)
}

type autoTypeConfigHello struct{}

// Method() KV should contain type string
func (autoTypeConfigHello) Method() paths.Path[string] {
	return paths.NewPath("wagtest/Config/Hello/Method", codecs.NewJsonCodec[string]())
}

// Get fetches all fields of NestedExternal in one or more transactions pinned to the same etcd revision.
func (a autoTypeConfigHello) GetWithFail(ctx context.Context, cli *v3.Client, failEarly bool, opts ...tetcd.TxnOp) (result config.NestedExternal, err error) {
	txn0 := tetcd.NewTxn(ctx, cli, opts...)
	h0_0 := tetcd.GetTx(txn0.Then(), a.Method())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Method, err = h0_0.Value()
	if err != nil && failEarly {
		return result, err
	}
	return result, nil
}
func (a autoTypeConfigHello) Get(ctx context.Context, cli *v3.Client, opts ...tetcd.TxnOp) (result config.NestedExternal, err error) {
	return a.GetWithFail(ctx, cli, false, opts...)
}

// Watch returns a Watcher that emits the full NestedExternal struct whenever any sub-key changes.
func (a autoTypeConfigHello) Watch(ctx context.Context, cli *v3.Client) *watch.Watcher[config.NestedExternal] {
	return specialist.NewAllWatcher(ctx, cli, "wagtest/Config/Hello/", a.GetWithFail)
}

type autoTypeConfigServer struct{}

// Host() KV should contain type string
func (autoTypeConfigServer) Host() paths.Path[string] {
	return paths.NewPath("wagtest/Config/Server/Host", codecs.NewJsonCodec[string]())
}

// Port() KV should contain type int
func (autoTypeConfigServer) Port() paths.Path[int] {
	return paths.NewPath("wagtest/Config/Server/Port", codecs.NewJsonCodec[int]())
}

// Test() KV should contain type string
func (autoTypeConfigServer) Test() paths.Path[string] {
	return paths.NewPath("wagtest/Config/Server/Test", codecs.NewJsonCodec[string]())
}

// Toaster() KV should contain type string
func (autoTypeConfigServer) Toaster() paths.Path[string] {
	return paths.NewPath("wagtest/Config/Server/Toaster", codecs.NewJsonCodec[string]())
}

// Get fetches all fields of ServerConfig in one or more transactions pinned to the same etcd revision.
func (a autoTypeConfigServer) GetWithFail(ctx context.Context, cli *v3.Client, failEarly bool, opts ...tetcd.TxnOp) (result config.ServerConfig, err error) {
	txn0 := tetcd.NewTxn(ctx, cli, opts...)
	h0_0 := tetcd.GetTx(txn0.Then(), a.Host())
	h0_1 := tetcd.GetTx(txn0.Then(), a.Port())
	h0_2 := tetcd.GetTx(txn0.Then(), a.Test())
	h0_3 := tetcd.GetTx(txn0.Then(), a.Toaster())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Host, err = h0_0.Value()
	if err != nil && failEarly {
		return result, err
	}
	result.Port, err = h0_1.Value()
	if err != nil && failEarly {
		return result, err
	}
	result.Test, err = h0_2.Value()
	if err != nil && failEarly {
		return result, err
	}
	result.Toaster, err = h0_3.Value()
	if err != nil && failEarly {
		return result, err
	}
	return result, nil
}
func (a autoTypeConfigServer) Get(ctx context.Context, cli *v3.Client, opts ...tetcd.TxnOp) (result config.ServerConfig, err error) {
	return a.GetWithFail(ctx, cli, false, opts...)
}

// Watch returns a Watcher that emits the full ServerConfig struct whenever any sub-key changes.
func (a autoTypeConfigServer) Watch(ctx context.Context, cli *v3.Client) *watch.Watcher[config.ServerConfig] {
	return specialist.NewAllWatcher(ctx, cli, "wagtest/Config/Server/", a.GetWithFail)
}

type autoTypeConfigSomethingElse struct{}

// Extra() KV should contain type string
func (autoTypeConfigSomethingElse) Extra() paths.Path[string] {
	return paths.NewPath("wagtest/Config/SomethingElse/Extra", codecs.NewJsonCodec[string]())
}

// Method() KV should contain type string
func (autoTypeConfigSomethingElse) Method() paths.Path[string] {
	return paths.NewPath("wagtest/Config/SomethingElse/Method", codecs.NewJsonCodec[string]())
}

// Methods() is a map path with prefix wagtest/Config/SomethingElse/Methods, value type string
func (autoTypeConfigSomethingElse) Methods() paths.MapPath[string] {
	return paths.NewMapPath("wagtest/Config/SomethingElse/Methods", codecs.NewJsonCodec[string](), true)
}

type resultConfigSomethingElse struct {
	another.SomeType
	Extra   string
	Methods []string
}

// Get fetches all fields of resultConfigSomethingElse in one or more transactions pinned to the same etcd revision.
func (a autoTypeConfigSomethingElse) GetWithFail(ctx context.Context, cli *v3.Client, failEarly bool, opts ...tetcd.TxnOp) (result resultConfigSomethingElse, err error) {
	txn0 := tetcd.NewTxn(ctx, cli, opts...)
	h0_0 := tetcd.GetTx(txn0.Then(), a.Extra())
	h0_1 := tetcd.GetTx(txn0.Then(), a.Method())
	h0_2 := tetcd.ListTx(txn0.Then(), a.Methods())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Extra, err = h0_0.Value()
	if err != nil && failEarly {
		return result, err
	}
	result.Method, err = h0_1.Value()
	if err != nil && failEarly {
		return result, err
	}
	result.Methods, err = h0_2.Keys()
	if err != nil && failEarly {
		return result, err
	}
	return result, nil
}
func (a autoTypeConfigSomethingElse) Get(ctx context.Context, cli *v3.Client, opts ...tetcd.TxnOp) (result resultConfigSomethingElse, err error) {
	return a.GetWithFail(ctx, cli, false, opts...)
}

// Watch returns a Watcher that emits the full resultConfigSomethingElse struct whenever any sub-key changes.
func (a autoTypeConfigSomethingElse) Watch(ctx context.Context, cli *v3.Client) *watch.Watcher[resultConfigSomethingElse] {
	return specialist.NewAllWatcher(ctx, cli, "wagtest/Config/SomethingElse/", a.GetWithFail)
}

type autoTypeTLSAhh struct{}

// Method() KV should contain type string
func (autoTypeTLSAhh) Method() paths.Path[string] {
	return paths.NewPath("wagtest/Config/TLS/Ahh/Method", codecs.NewJsonCodec[string]())
}

// Get fetches all fields of SomeType in one or more transactions pinned to the same etcd revision.
func (a autoTypeTLSAhh) GetWithFail(ctx context.Context, cli *v3.Client, failEarly bool, opts ...tetcd.TxnOp) (result another.SomeType, err error) {
	txn0 := tetcd.NewTxn(ctx, cli, opts...)
	h0_0 := tetcd.GetTx(txn0.Then(), a.Method())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Method, err = h0_0.Value()
	if err != nil && failEarly {
		return result, err
	}
	return result, nil
}
func (a autoTypeTLSAhh) Get(ctx context.Context, cli *v3.Client, opts ...tetcd.TxnOp) (result another.SomeType, err error) {
	return a.GetWithFail(ctx, cli, false, opts...)
}

// Watch returns a Watcher that emits the full SomeType struct whenever any sub-key changes.
func (a autoTypeTLSAhh) Watch(ctx context.Context, cli *v3.Client) *watch.Watcher[another.SomeType] {
	return specialist.NewAllWatcher(ctx, cli, "wagtest/Config/TLS/Ahh/", a.GetWithFail)
}

type autoTypeNestedInTlsDoublyNested struct{}

// Arghh() KV should contain type string
func (autoTypeNestedInTlsDoublyNested) Arghh() paths.Path[string] {
	return paths.NewPath("wagtest/Config/TLS/NestedInTls/DoublyNested/Arghh", codecs.NewJsonCodec[string]())
}

type resultNestedInTlsDoublyNested struct {
	Arghh string
}

// Get fetches all fields of resultNestedInTlsDoublyNested in one or more transactions pinned to the same etcd revision.
func (a autoTypeNestedInTlsDoublyNested) GetWithFail(ctx context.Context, cli *v3.Client, failEarly bool, opts ...tetcd.TxnOp) (result resultNestedInTlsDoublyNested, err error) {
	txn0 := tetcd.NewTxn(ctx, cli, opts...)
	h0_0 := tetcd.GetTx(txn0.Then(), a.Arghh())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Arghh, err = h0_0.Value()
	if err != nil && failEarly {
		return result, err
	}
	return result, nil
}
func (a autoTypeNestedInTlsDoublyNested) Get(ctx context.Context, cli *v3.Client, opts ...tetcd.TxnOp) (result resultNestedInTlsDoublyNested, err error) {
	return a.GetWithFail(ctx, cli, false, opts...)
}

// Watch returns a Watcher that emits the full resultNestedInTlsDoublyNested struct whenever any sub-key changes.
func (a autoTypeNestedInTlsDoublyNested) Watch(ctx context.Context, cli *v3.Client) *watch.Watcher[resultNestedInTlsDoublyNested] {
	return specialist.NewAllWatcher(ctx, cli, "wagtest/Config/TLS/NestedInTls/DoublyNested/", a.GetWithFail)
}

type autoTypeTLSNestedInTls struct {
	DoublyNested autoTypeNestedInTlsDoublyNested
}

// Fronk() KV should contain type string
func (autoTypeTLSNestedInTls) Fronk() paths.Path[string] {
	return paths.NewPath("wagtest/Config/TLS/NestedInTls/Fronk", codecs.NewJsonCodec[string]())
}

// Number() KV should contain type int
func (autoTypeTLSNestedInTls) Number() paths.Path[int] {
	return paths.NewPath("wagtest/Config/TLS/NestedInTls/Number", codecs.NewJsonCodec[int]())
}

// Something() KV should contain type string
func (autoTypeTLSNestedInTls) Something() paths.Path[string] {
	return paths.NewPath("wagtest/Config/TLS/NestedInTls/Something", codecs.NewJsonCodec[string]())
}

type resultTLSNestedInTls struct {
	Number       int
	Something    string
	Fronk        string
	DoublyNested struct {
		Arghh string
	}
}

// Get fetches all fields of resultTLSNestedInTls in one or more transactions pinned to the same etcd revision.
func (a autoTypeTLSNestedInTls) GetWithFail(ctx context.Context, cli *v3.Client, failEarly bool, opts ...tetcd.TxnOp) (result resultTLSNestedInTls, err error) {
	txn0 := tetcd.NewTxn(ctx, cli, opts...)
	h0_0 := tetcd.GetTx(txn0.Then(), a.DoublyNested.Arghh())
	h0_1 := tetcd.GetTx(txn0.Then(), a.Fronk())
	h0_2 := tetcd.GetTx(txn0.Then(), a.Number())
	h0_3 := tetcd.GetTx(txn0.Then(), a.Something())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.DoublyNested.Arghh, err = h0_0.Value()
	if err != nil && failEarly {
		return result, err
	}
	result.Fronk, err = h0_1.Value()
	if err != nil && failEarly {
		return result, err
	}
	result.Number, err = h0_2.Value()
	if err != nil && failEarly {
		return result, err
	}
	result.Something, err = h0_3.Value()
	if err != nil && failEarly {
		return result, err
	}
	return result, nil
}
func (a autoTypeTLSNestedInTls) Get(ctx context.Context, cli *v3.Client, opts ...tetcd.TxnOp) (result resultTLSNestedInTls, err error) {
	return a.GetWithFail(ctx, cli, false, opts...)
}

// Watch returns a Watcher that emits the full resultTLSNestedInTls struct whenever any sub-key changes.
func (a autoTypeTLSNestedInTls) Watch(ctx context.Context, cli *v3.Client) *watch.Watcher[resultTLSNestedInTls] {
	return specialist.NewAllWatcher(ctx, cli, "wagtest/Config/TLS/NestedInTls/", a.GetWithFail)
}

type autoTypeConfigTLS struct {
	Ahh         autoTypeTLSAhh
	NestedInTls autoTypeTLSNestedInTls
}

// CertFile() KV should contain type string
func (autoTypeConfigTLS) CertFile() paths.Path[string] {
	return paths.NewPath("wagtest/Config/TLS/CertFile", codecs.NewJsonCodec[string]())
}

// Groups() is a slice map path with prefix wagtest/Config/TLS/Groups, value type string
func (autoTypeConfigTLS) Groups() paths.MapSlicePath[string] {
	return paths.NewMapSlicePath("wagtest/Config/TLS/Groups", codecs.NewJsonCodec[string](), true)
}

// KeyFile() KV should contain type string
func (autoTypeConfigTLS) KeyFile() paths.Path[string] {
	return paths.NewPath("wagtest/Config/TLS/KeyFile", codecs.NewJsonCodec[string]())
}

// Get fetches all fields of TLSConfig in one or more transactions pinned to the same etcd revision.
func (a autoTypeConfigTLS) GetWithFail(ctx context.Context, cli *v3.Client, failEarly bool, opts ...tetcd.TxnOp) (result config.TLSConfig, err error) {
	txn0 := tetcd.NewTxn(ctx, cli, opts...)
	h0_0 := tetcd.GetTx(txn0.Then(), a.Ahh.Method())
	h0_1 := tetcd.GetTx(txn0.Then(), a.CertFile())
	h0_2 := tetcd.DynamicCollectionTx(txn0.Then(), a.Groups())
	h0_3 := tetcd.GetTx(txn0.Then(), a.KeyFile())
	h0_4 := tetcd.GetTx(txn0.Then(), a.NestedInTls.DoublyNested.Arghh())
	h0_5 := tetcd.GetTx(txn0.Then(), a.NestedInTls.Fronk())
	h0_6 := tetcd.GetTx(txn0.Then(), a.NestedInTls.Number())
	h0_7 := tetcd.GetTx(txn0.Then(), a.NestedInTls.Something())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Ahh.Method, err = h0_0.Value()
	if err != nil && failEarly {
		return result, err
	}
	result.CertFile, err = h0_1.Value()
	if err != nil && failEarly {
		return result, err
	}
	result.Groups, err = h0_2.Keys()
	if err != nil && failEarly {
		return result, err
	}
	result.KeyFile, err = h0_3.Value()
	if err != nil && failEarly {
		return result, err
	}
	result.NestedInTls.DoublyNested.Arghh, err = h0_4.Value()
	if err != nil && failEarly {
		return result, err
	}
	result.NestedInTls.Fronk, err = h0_5.Value()
	if err != nil && failEarly {
		return result, err
	}
	result.NestedInTls.Number, err = h0_6.Value()
	if err != nil && failEarly {
		return result, err
	}
	result.NestedInTls.Something, err = h0_7.Value()
	if err != nil && failEarly {
		return result, err
	}
	return result, nil
}
func (a autoTypeConfigTLS) Get(ctx context.Context, cli *v3.Client, opts ...tetcd.TxnOp) (result config.TLSConfig, err error) {
	return a.GetWithFail(ctx, cli, false, opts...)
}

// Watch returns a Watcher that emits the full TLSConfig struct whenever any sub-key changes.
func (a autoTypeConfigTLS) Watch(ctx context.Context, cli *v3.Client) *watch.Watcher[config.TLSConfig] {
	return specialist.NewAllWatcher(ctx, cli, "wagtest/Config/TLS/", a.GetWithFail)
}

type autoTypeConfig struct {
	Dummy         autoTypeConfigDummy
	Hello         autoTypeConfigHello
	Server        autoTypeConfigServer
	SomethingElse autoTypeConfigSomethingElse
	TLS           autoTypeConfigTLS
}

// CompressMe() KV should contain type struct{Noot string; Toaster string}
func (autoTypeConfig) CompressMe() paths.Path[config.CompressedStruct] {
	return paths.NewPath("wagtest/Config/CompressMe", codecs.NewJsonCodec[config.CompressedStruct]())
}

// EnumMap() is a map path with prefix wagtest/Config/EnumMap, value type github.com/NHAS/tetcd/cmd/test/config.Enum
func (autoTypeConfig) EnumMap() paths.MapPath[config.Enum] {
	return paths.NewMapPath("wagtest/Config/EnumMap", codecs.NewJsonCodec[config.Enum](), false)
}

// Labels() is a map path with prefix wagtest/Config/Labels, value type string
func (autoTypeConfig) Labels() paths.MapPath[string] {
	return paths.NewMapPath("wagtest/Config/Labels", codecs.NewJsonCodec[string](), false)
}

// MapTest() is a map path with prefix wagtest/Config/MapTest, value type github.com/NHAS/tetcd/cmd/test/config.InnerMap
func (autoTypeConfig) MapTest() paths.MapPath[config.InnerMap] {
	return paths.NewMapPath("wagtest/Config/MapTest", codecs.NewJsonCodec[config.InnerMap](), false)
}

// Methods1() is a map path with prefix wagtest/Config/Methods1, value type string
func (autoTypeConfig) Methods1() paths.MapPath[string] {
	return paths.NewMapPath("wagtest/Config/Methods1", codecs.NewJsonCodec[string](), true)
}

// Name() KV should contain type string
func (autoTypeConfig) Name() paths.Path[string] {
	return paths.NewPath("wagtest/Config/Name", codecs.NewJsonCodec[string]())
}

// Tags() KV should contain type []string
func (autoTypeConfig) Tags() paths.Path[[]string] {
	return paths.NewPath("wagtest/Config/Tags", codecs.NewJsonCodec[[]string]())
}

var (
	Config = autoTypeConfig{}
	Differ = tree.NewTreeWithPrefix[config.Config]("wagtest")
)

// init() builds the tree structure to automatically apply diffs to etcd
func init() {
	Differ.Register(Config.CompressMe())
	Differ.Register(Config.Dummy.Something5())
	Differ.Register(Config.EnumMap())
	Differ.Register(Config.Hello.Method())
	Differ.Register(Config.Labels())
	Differ.Register(Config.MapTest())
	Differ.Register(Config.Methods1())
	Differ.Register(Config.Name())
	Differ.Register(Config.Server.Host())
	Differ.Register(Config.Server.Port())
	Differ.Register(Config.Server.Test())
	Differ.Register(Config.Server.Toaster())
	Differ.Register(Config.SomethingElse.Extra())
	Differ.Register(Config.SomethingElse.Method())
	Differ.Register(Config.SomethingElse.Methods())
	Differ.Register(Config.TLS.Ahh.Method())
	Differ.Register(Config.TLS.CertFile())
	Differ.Register(Config.TLS.Groups())
	Differ.Register(Config.TLS.KeyFile())
	Differ.Register(Config.TLS.NestedInTls.DoublyNested.Arghh())
	Differ.Register(Config.TLS.NestedInTls.Fronk())
	Differ.Register(Config.TLS.NestedInTls.Number())
	Differ.Register(Config.TLS.NestedInTls.Something())
	Differ.Register(Config.Tags())
}
