// Code generated by https://github.com/NHAS/tetcd, DO NOT EDIT.
package main

import (
	codecs "github.com/NHAS/tetcd/codecs"
	paths "github.com/NHAS/tetcd/paths"
)

type autoTypeConfigServer struct{}

// Host() KV should contain type string
func (autoTypeConfigServer) Host() paths.Path[string] {
	return paths.NewPath("wagtest/Config/Server/Host", codecs.NewJsonCodec[string]())
}

// Port() KV should contain type int
func (autoTypeConfigServer) Port() paths.Path[int] {
	return paths.NewPath("wagtest/Config/Server/Port", codecs.NewJsonCodec[int]())
}

type autoTypeConfigTLS struct{}

// CertFile() KV should contain type string
func (autoTypeConfigTLS) CertFile() paths.Path[string] {
	return paths.NewPath("wagtest/Config/TLS/CertFile", codecs.NewJsonCodec[string]())
}

// KeyFile() KV should contain type string
func (autoTypeConfigTLS) KeyFile() paths.Path[string] {
	return paths.NewPath("wagtest/Config/TLS/KeyFile", codecs.NewJsonCodec[string]())
}

type autoTypeConfig struct {
	Server autoTypeConfigServer
	TLS    autoTypeConfigTLS
}

// Labels() is a map path with prefix wagtest/Config/Labels, value type string
func (autoTypeConfig) Labels() paths.MapPath[string] {
	return paths.NewMapPath("wagtest/Config/Labels", codecs.NewJsonCodec[string]())
}

// Name() KV should contain type string
func (autoTypeConfig) Name() paths.Path[string] {
	return paths.NewPath("wagtest/Config/Name", codecs.NewJsonCodec[string]())
}

// Tags() KV should contain type []string
func (autoTypeConfig) Tags() paths.Path[[]string] {
	return paths.NewPath("wagtest/Config/Tags", codecs.NewJsonCodec[[]string]())
}

var Config = autoTypeConfig{}
